### ISSUE TITLE
NMRdb integration is broken

### ISSUE THREAD

**Issue by bergwerf** [molview/legacy#17]
The API has changed. You now need to supply a `script` parameter. E.g.: https://script.epfl.ch/script/Service/20160510/vDpGux3hsy?smiles=C1%3DCC%3DCC%3DC1

**Comment by hermanbergwerf** [comment]
NMRdb might be trying to block external requests. I think we should contact them first before building a bypass.

**Comment by hermanbergwerf** [comment]
The best solution is probably to remove NMR spectra from the menu for now.

**Comment by bergwerf** [comment]
This is something I intend to fix in a new version of MolView that is developed from scratch.
