### ISSUE TITLE
Export STL files

### ISSUE THREAD

**Issue by Alonsoo** [molview/legacy#20]
This is more of a feature request than an issue. Is there any way to export the 3D model in STL format or something similar?

**Comment by bergwerf** [comment]
Currently I am not implementing new features but I'll keep this thread open for suggestions or related ideas.

I suggest https://3dprint.nih.gov/discover for 3d printing. There is a plugin for Blender 3D to import molecule data called BioBlender. I also found this program: https://openwetware.org/wiki/UCSF_Chimera_for_3D_Printing. I am sure there are many more.

Technical: A potential way to implement this feature is to use 3Dmol (or GLmol, MolView still uses GLmol which was forked by 3Dmol, 3Dmol is now preferred) and use a STL scene exporter for Three.js.

**Comment by bergwerf** [comment]
I am working on a new version that is designed from scratch. This is one of the features I intend to implement there in the future.
