### ISSUE TITLE
Embed 2D Canvas

### ISSUE THREAD

**Issue by hariria** [molview/legacy#21]
Hi! I love the work you're doing with this project. I'm thinking about using it for something school related, do you know if its possible to embed 2D diagrams of the molecules?

**Comment by arealguru** [comment]
It would also be nice if the drawing on the Canvas could be converted to SMILES.

**Comment by bergwerf** [comment]
Hi, unfortunately there is no standard way to do this. You are of course free to extract it from the source code and use it under the terms of the AGPL. I started a project with someone that included a component like this sketcher (but designed from scratch), but unfortunately the project has been inactive for a while and its unfinished (also not open-source). You can find it here: http://visk23.com/.

`src/js/chem` and `src/js/molpad` should contain all sources to use the sketcher.

**Comment by hariria** [comment]
Sorry I'm not familiar with the AGPL license. What exactly does it allow me to do with this?

**Comment by bergwerf** [comment]
There are lots of details but I recommend you look on
https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)
