### ISSUE TITLE
Molview's Backend Seems to Be Overflowed

### ISSUE THREAD

**Issue by arealguru** [molview/legacy#22]
I'm trying to access molview.com but I am reaching an error:

503 Backend fetch failed

I'd appreciate if you could look into it.

Edit: It seems to be back up now. I was wondering, is there a certain amount of requests that cause it to be overflowed? I love the models, and I wanted to embed some models in my website, and I don't want the server to be overflowed.

**Comment by bergwerf** [comment]
Most work is done client side, so the server shouldn't encounter any issues. I added some PHP code to add metadata to the document (hoping that Google would include it in some search results), but this could be disabled (I thought I disabled it for 3D embedding, but I may be mistaken).

If this happens repeatedly, I will look into ways to optimize the site.
