### ISSUE TITLE
SMILES export for MolView?

### ISSUE THREAD

**Issue by q2apro** [molview/legacy#23]
> This repository ... is not actively maintained due to lacking financial support.

Sad to hear!

I just stumbled over MolView and OpenChemLib: https://cheminfo.github.io/openchemlib-js/examples/Editor.html

MolView's interface is amazing. The only thing missing seems to be a **SMILES Export**. Could this essential thing be added?

SMILES import exists as I could see in the code.

**Comment by bergwerf** [comment]
In the menu: `Tools > Information Card` Here you find both the canonical and isomeric SMILES.

**Comment by q2apro** [comment]
Thanks!

For this graphic:

![image](https://user-images.githubusercontent.com/6764548/69640649-63c8c780-1067-11ea-9b23-a825abc48fef.png)

I get Canonical SMILES:

    OC(=O)C=CC(=[OH2])O

and Isomeric SMILES:

    [H]OC1/C(/[H])=C(\C(=O)O[H]O=1)/[H]

But entering the SMILES code into the SMILESdrawer at http://doc.gdb.tools/smilesDrawer/sd/example/index_light.html I do not get similar results:

![image](https://user-images.githubusercontent.com/6764548/69640722-822ec300-1067-11ea-8d59-5075acb35de3.png)

**Comment by bergwerf** [comment]
Possibly because this is a rather strange molecule (hydrogen cannot form two bonds, oxygen usually doesn't form three bonds. I may have time to look into this later.

**Comment by bergwerf** [comment]
If you look closely you'll see its almost the same molecule except for the hydrogen connecting the two oxygens at the top (and somehow much to far zoomed in). I don't think this molecule exists in nature, and most programs deal a bit loosely with hydrogens (since they normally only exist to saturate other atoms with single bonds).

**Comment by q2apro** [comment]
Also other tools cannot render both SMILES codes:

http://hulab.rxnfinder.org/smi2img/
http://www.openmolecules.org/name2structure.html "Structure name not resolved"

Molecule image from https://www.chemielounge.de/2814/handelt-sich-bei-folgenden-abbildung-eine-bernsteinsaure → in English: succinic acid [C4H6O4] [E-363]

**Comment by q2apro** [comment]
Okay, trying the correct molecule now:

1. Graphic:

![image](https://user-images.githubusercontent.com/6764548/69641600-2d8c4780-1069-11ea-8965-89c7fe67676f.png)

2. Drawn with MolView:

![image](https://user-images.githubusercontent.com/6764548/69641631-3bda6380-1069-11ea-83e4-81d67874d04b.png)

3. Information Card in MolView:

![image](https://user-images.githubusercontent.com/6764548/69641673-4eed3380-1069-11ea-9921-f16d8feb6041.png)

4. SMILES in Information Card

```
Canonical SMILES 
C(CC(=O)O)C(=O)O

Isomeric SMILES 
C(CC(=O)O)C(=O)O
```

5. Both SMILES codes

- do not work in: http://doc.gdb.tools/smilesDrawer/sd/example/index_light.html
- Canonical shows something in: http://hulab.rxnfinder.org/smi2img/ (Isomeric does not work)
- Canonical shows something in: http://www.openmolecules.org/name2structure.html (Isomeric does not work)

---

By the way: **My main goal** is to find some text formats (like SMILES) for molecule representations to put them into the browser to be displayed in a clean way (standard format).
