### ISSUE TITLE
How to draw straight with Molview?

### ISSUE THREAD

**Issue by q2apro** [molview/legacy#24]
I have this graphic:
![image](https://user-images.githubusercontent.com/6764548/69639869-0d0ebe00-1066-11ea-8e91-97a029f5c857.png)

And would like to transfer it to MolView.

Drawing by hand gives me:

![image](https://user-images.githubusercontent.com/6764548/69639887-19931680-1066-11ea-8788-4e5c62f00b43.png)

If I click on the button "clean structure", it turns to:

![image](https://user-images.githubusercontent.com/6764548/69639921-2ca5e680-1066-11ea-9f32-2535141a54a4.png)

But I would like to keep the positions of the atoms.

How to straighten the lines then?

**Comment by bergwerf** [comment]
Unfortunately thats not possible. The best you can do is use the move tool to manually reposition atoms. Straightening 2D coordinates in a way that preserved the 'topology' is a harder problem that you may think ;) (If you have a suitable algorithm in JavaScript, please let me know!). A possible way around this would be to 'snap' atoms to certain angles/distances when drawing.

**Comment by q2apro** [comment]
Idea: Kind of snapping would be to draw lines in 5° angles, while "aiming" (drawing) with the mouse :)

**Comment by bergwerf** [comment]
By the way, you can snap to fixed angles when you select an element, click on an existing atom, and then drag away from that atom.
