### ISSUE TITLE
Not an issue, just need help

### ISSUE THREAD

**Issue by denjixx** [molview/legacy#26]
Can I ask for help on installing this whole thing. I'm new to coding and I'm definitely stuck because I do not understand the instructions in readme.md. I hope someone could help me because I need the whole thing for our classroom instruction in Chemistry. We are not allowed to use the internet during class instruction, and I believe this thing is the most user-friendly.

Thank you so much!

**Comment by bergwerf** [comment]
This program is a bit of a beast (with dependencies on Apache, PHP, node, etc.) and it has not been maintained for years, so this is a bit difficult. I didn't design it to be easy to deploy lets say ;). Of course you could try to convince your school to enable a whitelist (such that certain sites of particular educational value are accessible). Note that without internet access MolView cannot resolve 3D structures or search for molecules, you can only sketch.

If the sketching functionality is enough for you, I could point to some similar applications that are easier to get on your machine.


If you really do want to try to get it running on your machine anyway, a first step is to search for instructions on installing Apache/PHP. If you are successful feel free to write me an email so I can give some pointers to carry on.
